# デフォルトのMarkdownlintルールセットを有効にしてから個別に無効化する
default: true
# 外部の設定ファイルを読み込まず、このファイルのみで完結させる
extends: null
# 文中の連続した空行を許容する
MD012: false
# 行の最大文字数制限をなくす
MD013: false
# 引用内で複数の空行を許容する
MD028: false
# ファイル冒頭に見出しがなくても許容する
MD041: false
